### ISSUE TITLE
Error: ERR unknown command 'eval' in chat example

### ISSUE THREAD

**Issue by jasonm** [derbyjs/derby#1]
Howdy!

I've been following derby for a little bit, and saw your presentation at KRTconf.  (Great presentation!)  I really like the direction you're going.

I'm pretty fresh to node (been doing Ruby and Rails the past few years, and Backbone the past ~6 months) and am trying to run through the derby examples.

When I run the chat example, and type into the username box in the browser, I get the following:

```
[master][~/dev/derby/examples/chat] node server.js 
   info  - socket.io started
Express server started in development mode
Go to: http://localhost:3002/
   debug - client authorized
   info  - handshake authorized 2025404070337778023
   debug - setting request GET /socket.io/1/websocket/2025404070337778023
   debug - set heartbeat interval for client 2025404070337778023
   debug - client authorized for 
   debug - websocket writing 1::
   debug - websocket writing 5:::{"name":"txnNum","args":[0]}
   debug - websocket writing 5:::{"name":"txnErr","args":[{"stack":"Error: ERR unknown command 'eval'\n    at RedisReplyParser.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:78:27)\n    at RedisReplyParser.emit (events.js:64:17)\n    at RedisReplyParser.send_error (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:265:14)\n    at RedisReplyParser.execute (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:124:22)\n    at RedisClient.on_data (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:358:27)\n    at Socket.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:93:14)\n    at Socket.emit (events.js:64:17)\n    at Socket._onReadable (net.js:672:14)\n    at IOWatcher.onReadable [as callback] (net.js:177:10)","message":"ERR unknown command 'eval'"},"3.29"]}
   debug - websocket writing 5:::{"name":"txnErr","args":[{"stack":"Error: ERR unknown command 'eval'\n    at RedisReplyParser.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:78:27)\n    at RedisReplyParser.emit (events.js:64:17)\n    at RedisReplyParser.send_error (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:265:14)\n    at RedisReplyParser.execute (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:124:22)\n    at RedisClient.on_data (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:358:27)\n    at Socket.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:93:14)\n    at Socket.emit (events.js:64:17)\n    at Socket._onReadable (net.js:672:14)\n    at IOWatcher.onReadable [as callback] (net.js:177:10)","message":"ERR unknown command 'eval'"},"3.30"]}
   debug - websocket writing 5:::{"name":"txnErr","args":[{"stack":"Error: ERR unknown command 'eval'\n    at RedisReplyParser.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:78:27)\n    at RedisReplyParser.emit (events.js:64:17)\n    at RedisReplyParser.send_error (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:265:14)\n    at RedisReplyParser.execute (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:124:22)\n    at RedisClient.on_data (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:358:27)\n    at Socket.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:93:14)\n    at Socket.emit (events.js:64:17)\n    at Socket._onReadable (net.js:672:14)\n    at IOWatcher.onReadable [as callback] (net.js:177:10)","message":"ERR unknown command 'eval'"},"3.31"]}
   debug - websocket writing 5:::{"name":"txnErr","args":[{"stack":"Error: ERR unknown command 'eval'\n    at RedisReplyParser.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:78:27)\n    at RedisReplyParser.emit (events.js:64:17)\n    at RedisReplyParser.send_error (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:265:14)\n    at RedisReplyParser.execute (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:124:22)\n    at RedisClient.on_data (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:358:27)\n    at Socket.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:93:14)\n    at Socket.emit (events.js:64:17)\n    at Socket._onReadable (net.js:672:14)\n    at IOWatcher.onReadable [as callback] (net.js:177:10)","message":"ERR unknown command 'eval'"},"3.32"]}
   debug - websocket writing 5:::{"name":"txnErr","args":[{"stack":"Error: ERR unknown command 'eval'\n    at RedisReplyParser.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:78:27)\n    at RedisReplyParser.emit (events.js:64:17)\n    at RedisReplyParser.send_error (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:265:14)\n    at RedisReplyParser.execute (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/lib/parser/javascript.js:124:22)\n    at RedisClient.on_data (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:358:27)\n    at Socket.<anonymous> (/Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/redis/index.js:93:14)\n    at Socket.emit (events.js:64:17)\n    at Socket._onReadable (net.js:672:14)\n    at IOWatcher.onReadable [as callback] (net.js:177:10)","message":"ERR unknown command 'eval'"},"3.33"]}
```

My node and npm information:

```
[master][~/dev/derby/examples/chat] npm --version
1.0.105
[master][~/dev/derby/examples/chat] node --version
v0.4.12
[master][~/dev/derby/examples/chat] npm ls
npm WARN es5-shim@1.2.10 package.json: bugs['web'] should probably be bugs['url']
npm WARN seq >=0.1.7 Unmet dependency in /Users/jasonmorrison/dev/derby/examples/chat/node_modules/derby/node_modules/racer/node_modules/browserify/node_modules/detective/node_modules/findit
derby-chat-example@0.0.0 /Users/jasonmorrison/dev/derby/examples/chat
├── coffee-script@1.1.3 
├─┬ connect-gzip@0.1.5 
│ ├─┬ connect@1.7.3 
│ │ └── qs@0.3.2 
│ └── mime@1.2.4 
├─┬ derby@0.1.1 
│ ├── commander@0.2.1 
│ ├── mkdirp@0.0.7 
│ ├── nib@0.2.0 
│ ├── qs@0.3.2 
│ ├─┬ racer@0.1.1 
│ │ ├─┬ browserify@1.7.7 
│ │ │ ├── commondir@0.0.0 
│ │ │ ├─┬ detective@0.0.3 
│ │ │ │ ├─┬ burrito@0.2.11 
│ │ │ │ │ ├── traverse@0.5.2 
│ │ │ │ │ └── uglify-js@1.0.7 
│ │ │ │ └─┬ findit@0.1.0  extraneous
│ │ │ │   └── UNMET DEPENDENCY seq >=0.1.7
│ │ │ ├── nub@0.0.0 
│ │ │ ├─┬ optimist@0.2.8 
│ │ │ │ └── wordwrap@0.0.2 
│ │ │ └── resolve@0.0.4 
│ │ ├── es5-shim@1.2.10 
│ │ ├── redis@0.6.7 
│ │ ├─┬ share@0.4.1 
│ │ │ ├─┬ connect@1.7.3 
│ │ │ │ └── mime@1.2.4 
│ │ │ ├── hat@0.0.3 
│ │ │ ├── mustache@0.3.1-dev  extraneous
│ │ │ ├─┬ optimist@0.2.8 
│ │ │ │ └── wordwrap@0.0.2 
│ │ │ └── redis@0.6.7  extraneous
│ │ ├─┬ socket.io@0.8.7 
│ │ │ └── policyfile@0.0.4 
│ │ └─┬ socket.io-client@0.8.7 
│ │   ├── uglify-js@1.0.6 
│ │   ├── websocket-client@1.0.0 
│ │   └── xmlhttprequest@1.2.2 
│ ├─┬ stylus@0.19.2 
│ │ ├── cssom@0.2.0 
│ │ └── growl@1.1.0 
│ └── uglify-js@1.1.1 
└─┬ express@2.5.0 
  ├── connect@1.7.3 
  ├── mime@1.2.4 
  ├── mkdirp@0.0.7 
  └── qs@0.3.2 
```

In the browser, I get an exception:

```

ready(function(model) {
    var displayTime, i, message, messagePath, months, time, _len, _ref2;
    months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    displayTime = function(time) {
      var hours, minutes, period;
      time = new Date(time);
      hours = time.getHours();
      period = hours < 12 ? ' am, ' : ' pm, ';
      hours = (hours % 12) || 12;
      minutes = time.getMinutes();
      if (minutes < 10) minutes = '0' + minutes;
      return hours + ':' + minutes + period + months[time.getMonth()] + ' ' + time.getDate() + ', ' + time.getFullYear();
    };
    _ref2 = model.get('_room.messages');
    for (i = 0, _len = _ref2.length; i < _len; i++) {
      //
      // On the line above: gen/L99FClvcujfbSS1m7aECAQ.js:3156 Uncaught TypeError: Cannot read property 'length' of undefined
      //
      message = _ref2[i];
      messagePath = "_room.messages." + i;
      if (time = model.get(messagePath + '.time')) {
        model.set(messagePath + '._displayTime', displayTime(time));
      }
    }
```

**Comment by Deepakchawla** [comment]
I am getting same error and below is result of my `pip freeze` command

asgi-redis==1.4.3
asgiref==1.1.2
attrs==17.2.0
autobahn==17.9.2
Automat==0.6.0
channels==1.1.8
constantly==15.1.0
daphne==1.3.0
Django==1.8.14
hyperlink==17.3.1
incremental==17.5.0
msgpack-python==0.4.8
olefile==0.44
Pillow==4.2.1
pypiwin32==219
pytz==2017.2
redis==2.10.6
six==1.11.0
SQLAlchemy==1.1.14
Twisted==17.5.0
txaio==2.8.2
zope.interface==4.4.2

I am using windows 7 and IntelliJ IDEA 2017.1 x64.

Can anyone help me..??
