### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by maggnus** [derbyjs/derby#530]
After multiple page refresh (Ctrl+R) I received error:

56308 listening. Go to: http://localhost:3000/
(node) warning: possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Backend.addListener (events.js:239:17)
  at doneInitialization (/Users/maggnus/Hlam/testproj/node_modules/racer-highway/lib/server/index.js:150:11)
  at WebSocketServer.<anonymous> (/Users/maggnus/Hlam/testproj/node_modules/racer-highway/lib/server/index.js:101:5)
  at emitOne (events.js:77:13)
  at WebSocketServer.emit (events.js:169:7)
  at /Users/maggnus/Hlam/testproj/node_modules/racer-highway/lib/server/index.js:121:13
  at completeHybiUpgrade2 (/Users/maggnus/Hlam/testproj/node_modules/ws/lib/WebSocketServer.js:237:5)
  at completeHybiUpgrade1 (/Users/maggnus/Hlam/testproj/node_modules/ws/lib/WebSocketServer.js:262:13)
  at WebSocketServer.handleHybiUpgrade (/Users/maggnus/Hlam/testproj/node_modules/ws/lib/WebSocketServer.js:290:3)
  at WebSocketServer.handleUpgrade (/Users/maggnus/Hlam/testproj/node_modules/ws/lib/WebSocketServer.js:147:26)
  at next (/Users/maggnus/Hlam/testproj/node_modules/racer-highway/lib/server/index.js:119:11)
  at Object.session (/Users/maggnus/Hlam/testproj/node_modules/express-session/index.js:397:7)
  at Server.upgrade (/Users/maggnus/Hlam/testproj/node_modules/racer-highway/lib/server/index.js:113:21)
  at emitThree (events.js:97:13)
  at Server.emit (events.js:175:7)
  at onParserExecuteCommon (_http_server.js:400:14)
  at HTTPParser.onParserExecute (_http_server.js:368:5)

Packages:
  "dependencies":
    "async": "^1.5.2",
    "body-parser": "^1.14.2",
    "chalk": "^1.1.1",
    "coffee-script": "^1.10.0",
    "coffeeify": "^2.0.1",
    "compression": "^1.6.1",
    "connect-mongo": "^0.8.2",
    "cookie-parser": "^1.4.1",
    "derby": "^0.8.0",
    "derby-debug": "^0.1.0",
    "derby-router": "^0.3.3",
    "derby-stylus": "^0.1.0",
    "express": "^4.13.4",
    "express-session": "^1.13.0",
    "racer-bundle": "^0.2.4",
    "racer-highway": "^7.0.0",
    "redis-url": "^1.2.1",
    "serve-favicon": "^2.3.0",
    "serve-static": "^1.10.2",
    "sharedb-mongo": "^0.8.7",
    "sharedb-redis-pubsub": "^0.3.1"

**Comment by psirenny** [comment]
I think this issue pertains to [racer-highway](https://github.com/derbyparty/racer-highway) and not derby core.

**Comment by droganov** [comment]
yes, it's from highway

**Comment by paradoxina** [comment]
how often the press сtrl+r?

**Comment by maggnus** [comment]
About 15 times with 1 second interval.

The same issue https://github.com/derbyparty/racer-highway/issues/8
